# DAP Lab 4

### 1) Create a text file and manually add some data to the file 

In [6]:
# Python program to illustrate 
# Append vs write mode 
file = open("myfile.txt","w") 
L = "This is Lagos\nThis is Abuja\nThis is Benin\n"
file.write(L)
file.close() 

### 2) Write Python code to open the file for write only access and attempt to read the contents of the file 

### 3) Note the type of Error that has been raised.

In [7]:
file = open("myfile.txt","w") 
file.readlines()
file.close() 

UnsupportedOperation: not readable

### 4) Modify your code to use a try / except / finally construct that will catch the exception, print a userfriendly error message, and clean up the file resource 

In [10]:
import io

try:
    file = open("myfile.txt","w") 
    file.readlines()
    file.close()
except io.UnsupportedOperation as err:
    print(err)
finally:
    print("Finally Block")
    file.close()

not readable
Finally Block


### 5) Investigate how you would create your own Exception class. Then create your own Exception class and use it in your code from the previous exercise. 

In [19]:
class CustomException(Exception):
     def __init__(self):
         default_message = 'This is a default message!'
         super().__init__(default_message)

In [21]:
try:
    file = open("myfile.txt","w") 
    file.readlines()
    file.close()
except:
    print('Except Block')
finally:
    raise CustomException()
    file.close()

Except Block


CustomException: This is a default message!

## NumPy Exercise 1

### 1) Create an array with the arange function and reshape the array as follows: b = arange(24).reshape(2,3,4) This gives us a 3-dimensional data structure – you can think of it as being like 2 spreadsheet sheets where each sheet contains 3 rows of data and each row contains 4 columns. Using indexing and slicing perform the following tasks:

In [30]:
import numpy as np

b = np.arange(24).reshape(2,3,4)

print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


### i) Choose the first set of 3 rows and 4 columns of data

In [25]:
print(b[0])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### ii) Choose the second row of data from the second set of 3 rows of data

In [27]:
print(b[1][1])

[16 17 18 19]


### iii) Choose all the data from the second column for both the first and second sets of rows and columns of data 

In [29]:
print(b[:,:,1])

[[ 1  5  9]
 [13 17 21]]


### 2) Use the ravel function to flatten the data. What’s the difference between ravel and flatten? 

In [31]:
ravelOutput = np.ravel(b)

print(ravelOutput)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [33]:
flattenOutput = b.flatten()

print(flattenOutput)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### 3) Reshape the data so that there are 6 rows of 4 columns per row.

In [34]:
reshapeOutput = b.reshape(6,4)

print(reshapeOutput)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### 4) Get the transpose of the new data structure. 

In [37]:
transposedOutput = b.T

print(transposedOutput)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


### 5) Restack the rows of the transposed data structure in reverse order (hint: look at the row_stack function).

In [43]:
StackedRows = np.row_stack(transposedOutput[::-1])

print(StackedRows)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


### 6) Split the resulting data structure horizontally (hint: look at the hsplit function). 

In [46]:
SplitArray = np.hsplit(b, 3)

print(SplitArray)

[array([[[ 0,  1,  2,  3]],

       [[12, 13, 14, 15]]]), array([[[ 4,  5,  6,  7]],

       [[16, 17, 18, 19]]]), array([[[ 8,  9, 10, 11]],

       [[20, 21, 22, 23]]])]


## NumPy Exercise 2

###  NOTE: The AAPL.csv contains some stock price data for Apple.           The MSFT.csv contains some stock price data for Microsoft. 

### 1) Use the loadtxt command to load data from AAPL.csv from columns 5 and 7 (i.e., the close price and the volume).

In [54]:
import numpy as np

columnFiveSeven = np.loadtxt('AAPL.csv', delimiter=',', dtype='float,int', usecols=(4, 6), skiprows=1, unpack=True)

print(columnFiveSeven)

[array([223.770004, 226.869995, 216.360001, 214.449997, 222.110001,
       217.360001, 222.149994, 221.190002, 216.020004, 219.309998,
       220.649994, 222.729996, 215.089996, 219.800003, 216.300003,
       212.240005, 213.300003, 218.860001, 222.220001, 207.479996,
       201.589996, 203.770004, 209.949997, 208.490005, 204.470001,
       194.169998, 192.229996, 186.800003, 191.410004, 193.529999,
       185.860001, 176.979996, 176.779999, 172.289993, 174.619995,
       174.240005, 180.940002, 179.550003, 178.580002, 184.820007,
       176.690002, 174.720001, 168.490005, 169.600006, 168.630005,
       169.100006, 170.949997, 165.479996, 163.940002, 166.070007,
       160.889999, 156.830002, 150.729996, 146.830002, 157.169998,
       156.149994, 156.229996, 157.740005, 157.919998, 142.190002,
       148.259995, 147.929993, 150.75    , 153.309998, 153.800003,
       152.289993, 150.      , 153.070007, 154.940002, 155.860001,
       156.820007, 153.300003, 153.919998, 152.699997, 157.75

### 2) Based on the data provided, calculate the volume weighted average price for the stock (i.e., calculate the average price using the volume as weight values). 

In [65]:
average_weighted_price = np.average(columnFiveSeven[0], axis= 0, weights= columnFiveSeven[1])
print(f"Average Weighted Price => {average_weighted_price}")

Average Weighted Price => 190.02952578964312


### 3) Calculate the median value of the closing prices (hint: use the median function). 

In [67]:
median_close_price = np.median(columnFiveSeven[0])
print(f"Median Close Price => {median_close_price}")

Median Close Price => 197.0


### 4) Calculate the variance value of the closing prices. 

In [68]:
variance_close_price = np.var(columnFiveSeven[0])
print(f"Variance Close Price => {variance_close_price}")

Variance Close Price => 432.8804568188714


### 5) Again, use the loadtxt command to load data from columns 3 and 4 (i.e., the high prices and the low prices).

In [70]:
import numpy as np

LowHigh = np.loadtxt('AAPL.csv', delimiter=',', dtype='float,float', usecols=(2, 3), skiprows=1, unpack=True)

print(LowHigh)

[array([224.800003, 227.270004, 226.350006, 219.5     , 222.880005,
       221.830002, 222.990005, 222.639999, 219.740005, 221.259995,
       223.360001, 223.25    , 224.229996, 221.380005, 220.190002,
       219.690002, 215.179993, 220.449997, 222.360001, 213.649994,
       204.389999, 204.720001, 210.059998, 210.119995, 206.009995,
       199.850006, 197.179993, 194.479996, 191.970001, 194.970001,
       190.699997, 181.470001, 180.270004, 176.600006, 174.949997,
       174.770004, 181.289993, 182.800003, 180.330002, 184.940002,
       182.389999, 174.779999, 174.490005, 170.089996, 171.789993,
       171.919998, 172.570007, 169.080002, 168.350006, 167.529999,
       167.449997, 162.110001, 158.160004, 151.550003, 157.229996,
       156.770004, 158.520004, 159.360001, 158.850006, 145.720001,
       148.550003, 148.830002, 151.820007, 154.529999, 153.970001,
       153.699997, 151.270004, 153.389999, 155.880005, 157.660004,
       157.880005, 156.729996, 155.139999, 154.479996, 158.13

### 6) Use the max and min functions to get the highest high and the lowest low value. 

In [71]:
minHighPrice = np.min(LowHigh[0])

maxHighPrice = np.max(LowHigh[0])

print(f"Min and Max High Price => {minHighPrice, maxHighPrice}")

Min and Max High Price => (145.720001, 229.929993)


In [72]:
minLowPrice = np.min(LowHigh[1])

maxLowPrice = np.max(LowHigh[1])

print(f"Min and Max Low Price => {minLowPrice, maxLowPrice}")

Min and Max Low Price => (142.0, 225.839996)


### 7) Load data from column 5 of AAPL.csv. Also, load data from column 5 of MSFT.csv. 

In [73]:
import numpy as np

aaplCol5 = np.loadtxt('AAPL.csv', delimiter=',', dtype='float', usecols=(4), skiprows=1, unpack=True)

msftCol5 = np.loadtxt('MSFT.csv', delimiter=',', dtype='float', usecols=(4), skiprows=1, unpack=True)

print(aaplCol5)

[223.770004 226.869995 216.360001 214.449997 222.110001 217.360001
 222.149994 221.190002 216.020004 219.309998 220.649994 222.729996
 215.089996 219.800003 216.300003 212.240005 213.300003 218.860001
 222.220001 207.479996 201.589996 203.770004 209.949997 208.490005
 204.470001 194.169998 192.229996 186.800003 191.410004 193.529999
 185.860001 176.979996 176.779999 172.289993 174.619995 174.240005
 180.940002 179.550003 178.580002 184.820007 176.690002 174.720001
 168.490005 169.600006 168.630005 169.100006 170.949997 165.479996
 163.940002 166.070007 160.889999 156.830002 150.729996 146.830002
 157.169998 156.149994 156.229996 157.740005 157.919998 142.190002
 148.259995 147.929993 150.75     153.309998 153.800003 152.289993
 150.       153.070007 154.940002 155.860001 156.820007 153.300003
 153.919998 152.699997 157.759995 156.300003 154.679993 165.25
 166.440002 166.520004 171.25     174.179993 174.240005 170.940002
 170.410004 169.429993 170.889999 170.179993 170.800003 170.419998

In [74]:
print(msftCol5)

[110.849998 112.260002 106.160004 105.910004 109.57     107.599998
 111.       110.709999 108.5      108.660004 109.629997 108.099998
 102.32     108.300003 106.959999 103.849998 103.730003 106.809998
 105.919998 106.160004 107.510002 107.720001 111.959999 111.75
 109.57     106.870003 106.940002 104.970001 107.279999 108.290001
 104.620003 101.709999 103.110001 103.07     106.470001 107.139999
 111.120003 110.190002 110.889999 112.089996 108.519997 109.190002
 104.82     107.589996 108.589996 109.080002 109.449997 106.029999
 102.889999 103.970001 103.690002 101.510002  98.230003  94.129997
 100.559998 101.18     100.389999 101.57     101.120003  97.400002
 101.93     102.059998 102.800003 104.269997 103.599998 102.800003
 102.050003 105.010002 105.379997 106.120003 107.709999 105.68
 106.709999 106.199997 107.169998 105.080002 102.940002 106.379997
 104.43     102.779999 105.739998 107.220001 106.029999 105.269997
 105.669998 105.25     106.889999 106.809998 106.900002 108.220001
 10

### 8) Calculate the covariance matrix of the closing prices of AAPL and MSFT (hint: use the cov function).

In [75]:
import numpy as np

covMatrix = np.cov(aaplCol5,msftCol5)

print(covMatrix)

[[434.60508015 186.97834783]
 [186.97834783 184.73421932]]


### 9) View the values on the diagonal (hint: diagonal).

In [77]:
print(f"The diagonal values are => {np.cov(aaplCol5,msftCol5).diagonal()}")

The diagonal values are => [434.60508015 184.73421932]


### 10) Calculate the correlation coefficient of the closing prices of AAPL and MSFT (hint: corrcoef).

In [79]:
import numpy as np

corrCoefficient = np.corrcoef(aaplCol5,msftCol5)

print(corrCoefficient)

[[1.         0.65988802]
 [0.65988802 1.        ]]


## Regular Expresssions Exercise

### 1) Write a Python program that will identify URLs using regular expressions.

In [80]:
import re
regex = r"http[s]?:\/\/\w+\.com?"
testString = "https://google.comhttp://google.comhtts://google.comhttp:/google.com"
x = re.findall(regex, testString)
print(x)

['https://google.com', 'http://google.com']


In [82]:
# Python code to find the URL from an input string 
# Using the regular expression 
import re 
  
def Find(string): 
  
    # findall() has been used  
    # with valid conditions for urls in string 
    regex = r"(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'\".,<>?«»“”‘’]))"
    url = re.findall(regex,string)       
    return [x[0] for x in url] 
      
# Driver Code 
string = 'My Profile: https://auth.geeksforgeeks.org/user/Chinmoy%20Lenka/articles in the portal of http://www.geeksforgeeks.org/'
print("Urls: ", Find(string)) 

Urls:  ['https://auth.geeksforgeeks.org/user/Chinmoy%20Lenka/articles', 'http://www.geeksforgeeks.org/']


## Text Analytics Exercise

### 1) Complete the tutorial at https://data-flair.training/blogs/nltk-python-tutorial/

### To install NLTK, you can use Python pip-

In [83]:
!pip install nltk

### Then to import it, you can type in the interpreter-
### You must know about Python Libraries

In [84]:
import nltk

### Finally, to install packages from NLTK, you need to use its downloader. Try this-

In [85]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [88]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kenec\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [97]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\kenec\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [141]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kenec\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [145]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\kenec\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

## NLTK Python Tutorial – NLTK Tokenize Text

### a) NLTK Sentence Tokenizer - Let’s try tokenizing a sentence.

In [89]:
text="Today is a great day. It is even better than yesterday. And yesterday was the best day ever."
from nltk.tokenize import sent_tokenize
sent_tokenize(text)

['Today is a great day.',
 'It is even better than yesterday.',
 'And yesterday was the best day ever.']

In [90]:
sent_tokenize("Hi, how are you? I'm good, you? Great!")

['Hi, how are you?', "I'm good, you?", 'Great!']

In [91]:
nltk.sent_tokenize("Last night, I went to Mrs. Martinez's housewarming. It was a disaster.")

["Last night, I went to Mrs. Martinez's housewarming.", 'It was a disaster.']

In [92]:
sent_tokenize("Enchanté, comment allez-vous? Tres bien. Mersi, et vous?","french")

['Enchanté, comment allez-vous?', 'Tres bien.', 'Mersi, et vous?']

### Issues while tokenizing- One issue we face while tokenizing is abbreviations-

In [93]:
sent_tokenize("She holds an MDS. in Oral Pathology")

['She holds an MDS.', 'in Oral Pathology']

## b) NLTK Word Tokenizer - First, let’s tokenize text in NLTK Python Tutorial.

In [94]:
nltk.word_tokenize(text)

['Today',
 'is',
 'a',
 'great',
 'day',
 '.',
 'It',
 'is',
 'even',
 'better',
 'than',
 'yesterday',
 '.',
 'And',
 'yesterday',
 'was',
 'the',
 'best',
 'day',
 'ever',
 '.']

### Find Synonyms From NLTK WordNet - WordNet is an NLP database with synonyms, antonyms, and brief definitions. We downloaded this with the NLTK downloader.

In [98]:
from nltk.corpus import wordnet
syn=wordnet.synsets('love')
syn

[Synset('love.n.01'),
 Synset('love.n.02'),
 Synset('beloved.n.01'),
 Synset('love.n.04'),
 Synset('love.n.05'),
 Synset('sexual_love.n.02'),
 Synset('love.v.01'),
 Synset('love.v.02'),
 Synset('love.v.03'),
 Synset('sleep_together.v.01')]

### Let’s choose the first member from this-

In [99]:
syn[0].definition()

'a strong positive emotion of regard and affection'

In [100]:
syn[0].examples()

['his love for his work', 'children need a lot of love']

### But love isn’t the only thing we’re chasing after. Do you know the meaning of life? 42?

In [101]:
syn=wordnet.synsets('life')
syn[0].definition()

'a characteristic state or mode of living'

In [102]:
syn[0].examples()

['social life', 'city life', 'real life']

### Nope, still doesn’t answer our questions. But Python does a good job. Okay, one more example.

In [103]:
syn=wordnet.synsets('AI')
syn

[Synset('army_intelligence.n.01'),
 Synset('artificial_intelligence.n.01'),
 Synset('three-toed_sloth.n.01'),
 Synset('artificial_insemination.n.01')]

In [104]:
syn[1].definition()

'the branch of computer science that deal with writing computer programs that can solve problems creatively'

In [105]:
syn[1].examples()

['workers in AI hope to imitate or duplicate intelligence in computers and robots']

### To get the list of synonyms:

In [106]:
synonyms=[]
for syn in wordnet.synsets('AI'):
        for lemma in syn.lemmas():
               synonyms.append(lemma.name())
synonyms

['Army_Intelligence',
 'AI',
 'artificial_intelligence',
 'AI',
 'three-toed_sloth',
 'ai',
 'Bradypus_tridactylus',
 'artificial_insemination',
 'AI']

### Find Antonyms From NLTK WordNet - To get the list of antonyms, we first need to check the lemmas- are there antonyms?

In [107]:
from nltk.corpus import wordnet
antonyms=[]
for syn in wordnet.synsets('depressed'):
        for l in syn.lemmas():
                 if l.antonyms():
                          antonyms.append(l.antonyms()[0].name())
antonyms

['elate']

In [109]:
for syn in wordnet.synsets('ugly'):
        for l in syn.lemmas():
                  if l.antonyms():
                            antonyms.append(l.antonyms()[0].name())
antonyms

['elate', 'beautiful', 'beautiful']

## NLTK Python Tutorial – Stemming NLTK

### Stemming involves removing affixes from words and returning the root. Search engines like Google use this to efficiently index pages. The most common algorithm for stemming is the PorterStemmer. Let’s take an example.

In [113]:
from nltk import PorterStemmer
stemmer = PorterStemmer()

stemmer.stem('loving')

'love'

In [114]:
stemmer.stem('trainee')

'traine'

In [115]:
stemmer.stem('syllabi')

'syllabi'

In [116]:
stemmer.stem('alibi')

'alibi'

In [117]:
stemmer.stem('formulae')

'formula'

In [118]:
stemmer.stem('criteria')

'criteria'

In [119]:
stemmer.stem('believes')

'believ'

In [120]:
stemmer.stem('writes')

'write'

In [121]:
stemmer.stem('writing')

'write'

In [122]:
stemmer.stem('write')

'write'

### Stemming Words from Other Languages

In [123]:
from nltk.stem import SnowballStemmer
SnowballStemmer.languages

('arabic',
 'danish',
 'dutch',
 'english',
 'finnish',
 'french',
 'german',
 'hungarian',
 'italian',
 'norwegian',
 'porter',
 'portuguese',
 'romanian',
 'russian',
 'spanish',
 'swedish')

In [124]:
rom_stemmer=SnowballStemmer('romanian')
rom_stemmer.stem('englezească') #English

'englez'

In [125]:
rom_stemmer.stem('cocoș') #Cocks

'cocoș'

In [126]:
rom_stemmer.stem('frigidere') #Refrigerators

'frigid'

In [127]:
rom_stemmer.stem('frigider') #Refrigerator

'frigider'

In [128]:
rom_stemmer.stem('goi') #Empty- plural

'goi'

In [129]:
rom_stemmer.stem('goale') #Empty- plural

'goal'

In [130]:
rom_stemmer.stem('frumoasă') #Beautiful- female

'frumoas'

In [131]:
rom_stemmer.stem('frumoase') #Beautiful- plural

'frumoas'

In [132]:
rom_stemmer.stem('frumoși') #Beautiful- plural

'frumoș'

### Python NLTK Tutorial – Lemmatizing NLTK Using WordNet
#### If you noticed, some words that stemming gave us weren’t actual words you could look up in the dictionary. So we come to lemmatizing- this will return real words. Let’s do this too.

In [133]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()
lemmatizer.lemmatize('believes')

'belief'

In [134]:
lemmatizer.lemmatize('this')

'this'

In [135]:
lemmatizer.lemmatize('believes',pos='v')

'believe'

In [136]:
lemmatizer.lemmatize('crossing',pos='a') #adjective

'crossing'

In [137]:
lemmatizer.lemmatize('crossing',pos='v') #verb

'cross'

In [138]:
lemmatizer.lemmatize('crossing',pos='n') #noun

'crossing'

In [139]:
lemmatizer.lemmatize('crossing',pos='r') #adverb

'crossing'

### Python NLTK Tutorial – NLTK Stop Words - We can filter NLTK stop words from text before processing it.

In [142]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [143]:
from nltk.corpus import stopwords
text="Today is a great day. It is even better than yesterday. And yesterday was the best day ever!"
stopwords=set(stopwords.words('english'))
from nltk.tokenize import word_tokenize
words=word_tokenize(text)
wordsFiltered=[]
for w in words:
        if w not in stopwords:
                 wordsFiltered.append(w)
wordsFiltered

['Today',
 'great',
 'day',
 '.',
 'It',
 'even',
 'better',
 'yesterday',
 '.',
 'And',
 'yesterday',
 'best',
 'day',
 'ever',
 '!']

### NLTK Python Tutorial – Speech Tagging - NLTK can classify words as verbs, nouns, adjectives, and more into one of the following classes:

In [146]:
import nltk
from nltk.tokenize import PunktSentenceTokenizer
text='I am a human being, capable of doing terrible things'
sentences=nltk.sent_tokenize(text)
for sent in sentences:
        print(nltk.pos_tag(nltk.word_tokenize(sent)))

[('I', 'PRP'), ('am', 'VBP'), ('a', 'DT'), ('human', 'JJ'), ('being', 'VBG'), (',', ','), ('capable', 'JJ'), ('of', 'IN'), ('doing', 'VBG'), ('terrible', 'JJ'), ('things', 'NNS')]


## References

### Python | Check for URL in a String | GeeksforGeeks - https://www.geeksforgeeks.org/python-check-url-string/

### NLTK Python Tutorial (Natural Language Toolkit) | DataFair - https://data-flair.training/blogs/nltk-python-tutorial/